export enum NavigationScreenNameEnum {
  COMMUNITY = 'community',
  CONTACT_US = 'contact-us',
  DEVELOPMENT = 'development',
  ERROR = 'error',
  LOGIN = 'login',
  LOGIN_VERIFICATION = 'login-verification',
  LOVE_POINTS = 'love-points',
  NEW_POST = 'new-post',
  PAGE_404 = '404',
  PAGE_500 = '500',
  POST = 'post',
  PRIVACY_POLICY = 'privacy-policy',
  PROFILE = 'profile',
  SIGNUP = 'signup',
  SIGNUP_VERIFICATION = 'signup-verification',
  SPLASH = 'splash',
  STUDIES = 'studies',
  TERMS_OF_SERVICE = 'terms-of-service',
}
